### ISSUE TITLE
gcc fails to compile generate_catalog.c

### ISSUE THREAD

**Issue by jweisbaum** [brownj4/Tetra#1]
Using gcc to compile generate_catolog.c I get the following errors:
`
generate_catalog.c:70:26: error: initializer element is not a compile-time
      constant
  ...= fmax(tan(max_fov*(1+max_fov_error)/2.0)/tan(max_fov/2.0),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generate_catalog.c:550:61: error: function definition is not allowed here
        void permute_features(int from_index, int to_index) {
                                                            ^
generate_catalog.c:597:9: warning: implicit declaration of function
      'permute_features' is invalid in C99 [-Wimplicit-function-declaration]
        permute_features(feature_index, i-1);
        ^
generate_catalog.c:623:52: error: function definition is not allowed here
    int compare_bins(const void *p, const void *q) {
                                                   ^
generate_catalog.c:636:74: error: use of undeclared identifier 'compare_bins'
    qsort(new_pattern.features, num_stars_in_pattern-2, sizeof(Feature), com...
                                                                         ^
generate_catalog.c:649:24: warning: implicit declaration of function
      'compare_bins' is invalid in C99 [-Wimplicit-function-declaration]
    pattern_rotation = compare_bins((void*)&first_feature,
                       ^
generate_catalog.c:1018:9: warning: implicit declaration of function 'fseeko64'
      is invalid in C99 [-Wimplicit-function-declaration]
        fseeko64(pattern_catalog_file,
        ^
generate_catalog.c:1057:5: warning: implicit declaration of function 'fseeko64'
      is invalid in C99 [-Wimplicit-function-declaration]
    fseeko64(bsc_file, 28, SEEK_SET);
    ^
4 warnings and 4 errors generated.
`

**Comment by brownj4** [comment]
Just verified it still works in the newest version of mingw-w64 on windows 10.  Here's the download link I used:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

And the settings in the installer:
Version 8.1.0
Architecture x86_64
Threads posix
Exception seh

From there I ran the mingw-w64.bat file and compiled as normal with gcc
Build revision 0

**Comment by jweisbaum** [comment]
Ok thanks for the steps and environment details. Also thanks for posting this, it's very cool. In your paper you compare Tetra with other star finding algos such as Pyramid. Did you write those yourself using their papers or were you able to find source for them somewhere? Thanks.

**Comment by brownj4** [comment]
Thank you!  I was able to find the original implementation of Pyramid in a publication (I believe it was Malak Samaan's thesis, although I had trouble tracking it down just now.), however I spoke with Professor Mortari about it, who expressed that the code was never meant to be released.  I therefore felt it would be unfair to make the comparison with an optimized implementation of Tetra, as the original pyramid code wasn't designed for performance.  I reimplemented both Pyramid and ND Star ID myself, in C, to make them faster and closer to what I believe is used in commercial devices.  My pyramid code also includes a toggle for the linear time cross-referencing I mentioned in the paper.  I haven't posted the code, as they aren't my algorithms.  They also aren't as clean and well commented as my Tetra code.  But I'm willing to ask permission from Prof. Mortari if you think it may be of benefit to post them here?

**Comment by jweisbaum** [comment]
I would love to see them if you can get the proper permissions. I think it would benefit the "next generation" of researchers/hobbyists to see implementations if the authors don't mind. I could even see a world where someone sponsors a benchmarking platform for people to test and compare implementations/algorithms.
