### ISSUE TITLE
Basic Use case errors 

### ISSUE THREAD

**Issue by randyg3000** [brownj4/Tetra#4]
Using BSC5 and Aurora image referenced in your Readme, on MacBook w/current OS X:
$ python3 tetra.py
number of stars in star table and sky maps: 1630
Traceback (most recent call last):
  File "tetra.py", line 242, in <module>
    fine_sky_map = np.zeros(len(stars) / fine_sky_map_fill_factor, dtype=np.uint16)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by brownj4** [comment]
Newer python 3 changes broke implicit integer conversions.  I've updated the python code and confirmed it now works in both Python 3.6.5 and Python 2.7.14.
